import bcrypt from 'bcryptjs';
import { db, type User, type Category, type Product } from './db';

const defaultUsers: User[] = [
  {
    name: 'Saadullah',
    username: 'Saadullah',
    password: bcrypt.hashSync('saad1234', 10),
    role: 'admin',
    email: 'saadullah@furnicraft.com',
    phone: '+92-300-0000001',
    status: 'active',
    permissions: ['dashboard', 'pos', 'products', 'inventory', 'reports', 'staff', 'customers'],
    createdAt: new Date()
  },
  {
    name: 'Samiullah',
    username: 'Samiullah',
    password: bcrypt.hashSync('sami0987', 10),
    role: 'admin',
    email: 'samiullah@furnicraft.com',
    phone: '+92-300-0000002',
    status: 'active',
    permissions: ['dashboard', 'pos', 'products', 'inventory', 'reports', 'staff', 'customers'],
    createdAt: new Date()
  },
  {
    name: 'Abdullah',
    username: 'Abdullah',
    password: bcrypt.hashSync('abd4567', 10),
    role: 'admin',
    email: 'abdullah@furnicraft.com',
    phone: '+92-300-0000003',
    status: 'active',
    permissions: ['dashboard', 'pos', 'products', 'inventory', 'reports', 'staff', 'customers'],
    createdAt: new Date()
  }
];

const defaultCategories: Category[] = [
  // Furniture
  { name: 'Double Bed', description: 'Double beds with cushioning, solid, sheet & wood mix options', icon: '🛏️', color: '#D4A853', status: 'active', sortOrder: 1 },
  { name: 'Single Bed', description: 'Single beds with cushioning, solid, sheet & wood mix options', icon: '🛏️', color: '#16A34A', status: 'active', sortOrder: 2 },
  { name: 'Sofa', description: 'Sofas including 5-seater and other sizes', icon: '🛋️', color: '#2563EB', status: 'active', sortOrder: 3 },
  { name: 'Dewan', description: 'Traditional dewan sets', icon: '🪑', color: '#D97706', status: 'active', sortOrder: 4 },
  { name: 'Table Set', description: 'Table sets for various purposes', icon: '🪑', color: '#7C3AED', status: 'active', sortOrder: 5 },
  { name: 'Coffee Set', description: 'Coffee table sets', icon: '☕', color: '#0891B2', status: 'active', sortOrder: 6 },
  { name: 'Dining Set', description: 'Dining table and chair sets', icon: '🍽️', color: '#DC2626', status: 'active', sortOrder: 7 },
  { name: 'Showcase', description: 'Display showcases and cabinets', icon: '🗄️', color: '#65A30D', status: 'active', sortOrder: 8 },
  { name: 'Cupboard', description: 'Storage cupboards and wardrobes', icon: '🚪', color: '#EA580C', status: 'active', sortOrder: 9 },
  { name: 'Shoe Rack', description: 'Shoe racks and organizers', icon: '👟', color: '#9333EA', status: 'active', sortOrder: 10 },
  { name: 'Console', description: 'Console tables and decorative pieces', icon: '�', color: '#0D9488', status: 'active', sortOrder: 11 },
  { name: 'Inventory', description: 'General furniture inventory items', icon: '📦', color: '#BE123C', status: 'active', sortOrder: 12 },
  // Carpentry Workshop
  { name: 'Nails', description: 'All types and sizes of nails', icon: '🔩', color: '#64748B', status: 'active', sortOrder: 13 },
  { name: 'Screws', description: 'All types and sizes of screws', icon: '🔧', color: '#475569', status: 'active', sortOrder: 14 },
  { name: 'Hinges', description: 'Door and cabinet hinges', icon: '�', color: '#334155', status: 'active', sortOrder: 15 },
  { name: 'Glue', description: 'Wood glue and adhesives', icon: '🧴', color: '#1E293B', status: 'active', sortOrder: 16 },
  { name: 'Epoxy', description: 'Epoxy resins and hardeners', icon: '🧪', color: '#0F172A', status: 'active', sortOrder: 17 },
  { name: 'Chipboard', description: 'Chipboard sheets for furniture', icon: '📋', color: '#D4A853', status: 'active', sortOrder: 18 },
  { name: 'Winboard', description: 'Winboard and particle boards', icon: '�', color: '#16A34A', status: 'active', sortOrder: 19 },
  { name: 'Lassani', description: 'Lassani board sheets', icon: '📋', color: '#2563EB', status: 'active', sortOrder: 20 },
  { name: 'Lamination', description: 'Lamination sheets and rolls', icon: '🎨', color: '#D97706', status: 'active', sortOrder: 21 },
  { name: 'Wood', description: 'Solid wood planks and boards', icon: '🪵', color: '#7C3AED', status: 'active', sortOrder: 22 },
  // Finishing
  { name: 'Thinner', description: 'Paint thinners and solvents', icon: '🧴', color: '#0891B2', status: 'active', sortOrder: 23 },
  { name: 'Sealer', description: 'Wood sealers and primers', icon: '🧴', color: '#DC2626', status: 'active', sortOrder: 24 },
  { name: 'Lacquer', description: 'Lacquer finishes and coatings', icon: '✨', color: '#65A30D', status: 'active', sortOrder: 25 },
  { name: 'Hardner', description: 'Paint and epoxy hardeners', icon: '⚗️', color: '#EA580C', status: 'active', sortOrder: 26 },
  { name: 'Sand Papers', description: 'Sand papers in all grit sizes', icon: '📄', color: '#9333EA', status: 'active', sortOrder: 27 },
  { name: 'Deco Paints', description: 'Decorative paints and coatings', icon: '�', color: '#0D9488', status: 'active', sortOrder: 28 }
];

const sampleProducts: Product[] = [
  // Double Bed - Cushioning
  {
    categoryId: 1,
    sku: 'BED-DBL-CUS-001',
    name: 'Double Bed - Cushioning Type A',
    subcategory: 'Cushioning',
    brand: 'Custom Furniture',
    description: 'Double bed with cushioning support',
    material: 'Wood + Cushioning',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 200, width: 150, height: 100, weight: 55 },
    costPrice: 25000,
    sellPrice: 35000,
    discountable: true,
    taxable: true,
    stock: 5,
    minStock: 2,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: true,
    createdAt: new Date()
  },
  // Double Bed - Solid
  {
    categoryId: 1,
    sku: 'BED-DBL-SLD-001',
    name: 'Double Bed - Solid Wood',
    subcategory: 'Solid',
    brand: 'Custom Furniture',
    description: 'Solid wood double bed frame',
    material: 'Solid Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 200, width: 150, height: 100, weight: 60 },
    costPrice: 30000,
    sellPrice: 42000,
    discountable: true,
    taxable: true,
    stock: 4,
    minStock: 2,
    maxStock: 12,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: true,
    createdAt: new Date()
  },
  // Double Bed - Sheet
  {
    categoryId: 1,
    sku: 'BED-DBL-SHT-001',
    name: 'Double Bed - Sheet Type',
    subcategory: 'Sheet',
    brand: 'Custom Furniture',
    description: 'Double bed with sheet base',
    material: 'Wood + Sheet',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 200, width: 150, height: 95, weight: 50 },
    costPrice: 22000,
    sellPrice: 32000,
    discountable: true,
    taxable: true,
    stock: 6,
    minStock: 2,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Double Bed - Wood Mix
  {
    categoryId: 1,
    sku: 'BED-DBL-MIX-001',
    name: 'Double Bed - Wood Mix',
    subcategory: 'Wood Mix',
    brand: 'Custom Furniture',
    description: 'Double bed with mixed wood construction',
    material: 'Mixed Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 200, width: 150, height: 100, weight: 58 },
    costPrice: 28000,
    sellPrice: 38000,
    discountable: true,
    taxable: true,
    stock: 5,
    minStock: 2,
    maxStock: 12,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Single Bed - Cushioning
  {
    categoryId: 2,
    sku: 'BED-SNG-CUS-001',
    name: 'Single Bed - Cushioning',
    subcategory: 'Cushioning',
    brand: 'Custom Furniture',
    description: 'Single bed with cushioning support',
    material: 'Wood + Cushioning',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 190, width: 100, height: 90, weight: 35 },
    costPrice: 15000,
    sellPrice: 22000,
    discountable: true,
    taxable: true,
    stock: 8,
    minStock: 3,
    maxStock: 20,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: true,
    createdAt: new Date()
  },
  // Single Bed - Solid
  {
    categoryId: 2,
    sku: 'BED-SNG-SLD-001',
    name: 'Single Bed - Solid Wood',
    subcategory: 'Solid',
    brand: 'Custom Furniture',
    description: 'Solid wood single bed frame',
    material: 'Solid Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 190, width: 100, height: 90, weight: 40 },
    costPrice: 18000,
    sellPrice: 26000,
    discountable: true,
    taxable: true,
    stock: 6,
    minStock: 2,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Single Bed - Sheet
  {
    categoryId: 2,
    sku: 'BED-SNG-SHT-001',
    name: 'Single Bed - Sheet Type',
    subcategory: 'Sheet',
    brand: 'Custom Furniture',
    description: 'Single bed with sheet base',
    material: 'Wood + Sheet',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 190, width: 100, height: 85, weight: 32 },
    costPrice: 14000,
    sellPrice: 20000,
    discountable: true,
    taxable: true,
    stock: 10,
    minStock: 3,
    maxStock: 20,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Single Bed - Wood Mix
  {
    categoryId: 2,
    sku: 'BED-SNG-MIX-001',
    name: 'Single Bed - Wood Mix',
    subcategory: 'Wood Mix',
    brand: 'Custom Furniture',
    description: 'Single bed with mixed wood construction',
    material: 'Mixed Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 190, width: 100, height: 90, weight: 38 },
    costPrice: 16000,
    sellPrice: 24000,
    discountable: true,
    taxable: true,
    stock: 7,
    minStock: 2,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Sofa 5 Seater
  {
    categoryId: 3,
    sku: 'SOF-5ST-001',
    name: 'Sofa 5 Seater',
    brand: 'Custom Furniture',
    description: '5-seater sofa for living room',
    material: 'Fabric + Wood',
    color: ['#1C1917', '#78716C', '#E7E5E4'],
    dimensions: { length: 250, width: 90, height: 85, weight: 50 },
    costPrice: 45000,
    sellPrice: 60000,
    discountable: true,
    taxable: true,
    stock: 4,
    minStock: 2,
    maxStock: 10,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: true,
    createdAt: new Date()
  },
  // Dewan
  {
    categoryId: 4,
    sku: 'DEW-001',
    name: 'Traditional Dewan',
    brand: 'Custom Furniture',
    description: 'Traditional style dewan set',
    material: 'Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 180, width: 80, height: 45, weight: 35 },
    costPrice: 18000,
    sellPrice: 28000,
    discountable: true,
    taxable: true,
    stock: 6,
    minStock: 2,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Table Set
  {
    categoryId: 5,
    sku: 'TBL-SET-001',
    name: 'Table Set',
    brand: 'Custom Furniture',
    description: 'Complete table set',
    material: 'Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 150, width: 80, height: 75, weight: 40 },
    costPrice: 25000,
    sellPrice: 35000,
    discountable: true,
    taxable: true,
    stock: 8,
    minStock: 3,
    maxStock: 20,
    unit: 'set',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Coffee Set
  {
    categoryId: 6,
    sku: 'COF-SET-001',
    name: 'Coffee Table Set',
    brand: 'Custom Furniture',
    description: 'Coffee table with side tables',
    material: 'Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 100, width: 60, height: 45, weight: 25 },
    costPrice: 15000,
    sellPrice: 22000,
    discountable: true,
    taxable: true,
    stock: 10,
    minStock: 3,
    maxStock: 25,
    unit: 'set',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Dining Set
  {
    categoryId: 7,
    sku: 'DIN-SET-001',
    name: 'Dining Set 6 Seater',
    brand: 'Custom Furniture',
    description: 'Complete dining set with table and chairs',
    material: 'Wood',
    color: ['#1C1917'],
    dimensions: { length: 180, width: 90, height: 75, weight: 80 },
    costPrice: 48000,
    sellPrice: 65000,
    discountable: true,
    taxable: true,
    stock: 7,
    minStock: 2,
    maxStock: 15,
    unit: 'set',
    images: [],
    status: 'active',
    featured: true,
    createdAt: new Date()
  },
  // Showcase
  {
    categoryId: 8,
    sku: 'SHW-001',
    name: 'Display Showcase',
    brand: 'Custom Furniture',
    description: 'Glass display showcase with lighting',
    material: 'Wood + Glass',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 120, width: 40, height: 180, weight: 45 },
    costPrice: 22000,
    sellPrice: 32000,
    discountable: true,
    taxable: true,
    stock: 5,
    minStock: 2,
    maxStock: 12,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Cupboard
  {
    categoryId: 9,
    sku: 'CUP-001',
    name: 'Storage Cupboard',
    brand: 'Custom Furniture',
    description: 'Multi-purpose storage cupboard',
    material: 'Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 100, width: 50, height: 180, weight: 60 },
    costPrice: 20000,
    sellPrice: 30000,
    discountable: true,
    taxable: true,
    stock: 8,
    minStock: 3,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Shoe Rack
  {
    categoryId: 10,
    sku: 'SHR-001',
    name: 'Shoe Rack',
    brand: 'Custom Furniture',
    description: 'Multi-tier shoe rack',
    material: 'Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 80, width: 30, height: 100, weight: 15 },
    costPrice: 5000,
    sellPrice: 8000,
    discountable: true,
    taxable: true,
    stock: 15,
    minStock: 5,
    maxStock: 30,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Console
  {
    categoryId: 11,
    sku: 'CON-001',
    name: 'Console Table',
    brand: 'Custom Furniture',
    description: 'Decorative console table',
    material: 'Wood',
    color: ['#1C1917', '#292524'],
    dimensions: { length: 120, width: 40, height: 75, weight: 25 },
    costPrice: 12000,
    sellPrice: 18000,
    discountable: true,
    taxable: true,
    stock: 8,
    minStock: 3,
    maxStock: 15,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Inventory
  {
    categoryId: 12,
    sku: 'INV-GEN-001',
    name: 'General Furniture Item',
    brand: 'Custom Furniture',
    description: 'General inventory furniture item',
    material: 'Wood',
    color: ['#1C1917'],
    dimensions: { length: 100, width: 50, height: 100, weight: 30 },
    costPrice: 15000,
    sellPrice: 22000,
    discountable: true,
    taxable: true,
    stock: 10,
    minStock: 3,
    maxStock: 20,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Carpentry Workshop Materials
  // Nails
  {
    categoryId: 13,
    sku: 'NAIL-1IN-001',
    name: 'Nails 1 inch',
    brand: 'Generic',
    description: '1 inch steel nails',
    material: 'Steel',
    color: ['#78716C'],
    dimensions: { length: 2.5, width: 0.3, height: 0.3, weight: 1 },
    costPrice: 200,
    sellPrice: 350,
    discountable: true,
    taxable: true,
    stock: 100,
    minStock: 20,
    maxStock: 500,
    unit: 'kg',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  {
    categoryId: 13,
    sku: 'NAIL-2IN-001',
    name: 'Nails 2 inch',
    brand: 'Generic',
    description: '2 inch steel nails',
    material: 'Steel',
    color: ['#78716C'],
    dimensions: { length: 5, width: 0.4, height: 0.4, weight: 1 },
    costPrice: 250,
    sellPrice: 400,
    discountable: true,
    taxable: true,
    stock: 80,
    minStock: 20,
    maxStock: 500,
    unit: 'kg',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Screws
  {
    categoryId: 14,
    sku: 'SCREW-1IN-001',
    name: 'Screws 1 inch',
    brand: 'Generic',
    description: '1 inch wood screws',
    material: 'Steel',
    color: ['#78716C'],
    dimensions: { length: 2.5, width: 0.4, height: 0.4, weight: 1 },
    costPrice: 300,
    sellPrice: 450,
    discountable: true,
    taxable: true,
    stock: 100,
    minStock: 20,
    maxStock: 500,
    unit: 'kg',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  {
    categoryId: 14,
    sku: 'SCREW-2IN-001',
    name: 'Screws 2 inch',
    brand: 'Generic',
    description: '2 inch wood screws',
    material: 'Steel',
    color: ['#78716C'],
    dimensions: { length: 5, width: 0.5, height: 0.5, weight: 1 },
    costPrice: 350,
    sellPrice: 500,
    discountable: true,
    taxable: true,
    stock: 80,
    minStock: 20,
    maxStock: 500,
    unit: 'kg',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Hinges
  {
    categoryId: 15,
    sku: 'HINGE-4IN-001',
    name: 'Door Hinges 4 inch',
    brand: 'Generic',
    description: '4 inch door hinges',
    material: 'Steel',
    color: ['#78716C'],
    dimensions: { length: 10, width: 3, height: 0.5, weight: 0.5 },
    costPrice: 150,
    sellPrice: 250,
    discountable: true,
    taxable: true,
    stock: 200,
    minStock: 50,
    maxStock: 1000,
    unit: 'piece',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Glue
  {
    categoryId: 16,
    sku: 'GLUE-WD-001',
    name: 'Wood Glue',
    brand: 'Fevicol',
    description: 'Premium wood adhesive',
    material: 'Adhesive',
    color: ['#FFFFFF'],
    dimensions: { length: 10, width: 5, height: 20, weight: 1 },
    costPrice: 500,
    sellPrice: 750,
    discountable: true,
    taxable: true,
    stock: 50,
    minStock: 10,
    maxStock: 100,
    unit: 'bottle',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Epoxy
  {
    categoryId: 17,
    sku: 'EPOXY-001',
    name: 'Epoxy Resin',
    brand: 'Generic',
    description: 'Clear epoxy resin',
    material: 'Resin',
    color: ['#FFFFFF'],
    dimensions: { length: 10, width: 5, height: 15, weight: 2 },
    costPrice: 1500,
    sellPrice: 2200,
    discountable: true,
    taxable: true,
    stock: 30,
    minStock: 5,
    maxStock: 50,
    unit: 'bottle',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Chipboard
  {
    categoryId: 18,
    sku: 'CHIP-8X4-001',
    name: 'Chipboard 8x4 feet',
    brand: 'Generic',
    description: '8x4 feet chipboard sheet',
    material: 'Chipboard',
    color: ['#D4A853'],
    dimensions: { length: 244, width: 122, height: 1.8, weight: 25 },
    costPrice: 2500,
    sellPrice: 3500,
    discountable: true,
    taxable: true,
    stock: 40,
    minStock: 10,
    maxStock: 100,
    unit: 'sheet',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Winboard
  {
    categoryId: 19,
    sku: 'WIN-8X4-001',
    name: 'Winboard 8x4 feet',
    brand: 'Generic',
    description: '8x4 feet winboard sheet',
    material: 'Winboard',
    color: ['#D4A853'],
    dimensions: { length: 244, width: 122, height: 1.8, weight: 22 },
    costPrice: 2200,
    sellPrice: 3200,
    discountable: true,
    taxable: true,
    stock: 40,
    minStock: 10,
    maxStock: 100,
    unit: 'sheet',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Lassani
  {
    categoryId: 20,
    sku: 'LASS-8X4-001',
    name: 'Lassani Board 8x4 feet',
    brand: 'Generic',
    description: '8x4 feet lassani board sheet',
    material: 'Lassani',
    color: ['#D4A853'],
    dimensions: { length: 244, width: 122, height: 1.2, weight: 18 },
    costPrice: 1800,
    sellPrice: 2800,
    discountable: true,
    taxable: true,
    stock: 50,
    minStock: 10,
    maxStock: 100,
    unit: 'sheet',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Lamination
  {
    categoryId: 21,
    sku: 'LAM-ROLL-001',
    name: 'Lamination Roll',
    brand: 'Generic',
    description: 'Decorative lamination roll',
    material: 'Lamination',
    color: ['#D4A853'],
    dimensions: { length: 1000, width: 122, height: 0.1, weight: 5 },
    costPrice: 1500,
    sellPrice: 2200,
    discountable: true,
    taxable: true,
    stock: 30,
    minStock: 5,
    maxStock: 50,
    unit: 'meter',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Wood
  {
    categoryId: 22,
    sku: 'WOOD-PLY-001',
    name: 'Plywood Sheet',
    brand: 'Generic',
    description: '8x4 feet plywood sheet',
    material: 'Plywood',
    color: ['#D4A853'],
    dimensions: { length: 244, width: 122, height: 1.8, weight: 30 },
    costPrice: 3500,
    sellPrice: 4800,
    discountable: true,
    taxable: true,
    stock: 60,
    minStock: 15,
    maxStock: 150,
    unit: 'sheet',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Finishing Materials
  // Thinner
  {
    categoryId: 23,
    sku: 'THIN-LTR-001',
    name: 'Paint Thinner',
    brand: 'Generic',
    description: 'Paint thinner solvent',
    material: 'Chemical',
    color: ['#FFFFFF'],
    dimensions: { length: 15, width: 10, height: 25, weight: 1 },
    costPrice: 800,
    sellPrice: 1200,
    discountable: true,
    taxable: true,
    stock: 40,
    minStock: 10,
    maxStock: 80,
    unit: 'liter',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Sealer
  {
    categoryId: 24,
    sku: 'SEAL-LTR-001',
    name: 'Wood Sealer',
    brand: 'Generic',
    description: 'Wood sealer and primer',
    material: 'Sealer',
    color: ['#FFFFFF'],
    dimensions: { length: 15, width: 10, height: 25, weight: 1 },
    costPrice: 1000,
    sellPrice: 1500,
    discountable: true,
    taxable: true,
    stock: 30,
    minStock: 8,
    maxStock: 60,
    unit: 'liter',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Lacquer
  {
    categoryId: 25,
    sku: 'LAC-LTR-001',
    name: 'Lacquer Finish',
    brand: 'Generic',
    description: 'High gloss lacquer finish',
    material: 'Lacquer',
    color: ['#FFFFFF'],
    dimensions: { length: 15, width: 10, height: 25, weight: 1 },
    costPrice: 1200,
    sellPrice: 1800,
    discountable: true,
    taxable: true,
    stock: 25,
    minStock: 5,
    maxStock: 50,
    unit: 'liter',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Hardner
  {
    categoryId: 26,
    sku: 'HARD-LTR-001',
    name: 'Paint Hardener',
    brand: 'Generic',
    description: 'Paint and epoxy hardener',
    material: 'Chemical',
    color: ['#FFFFFF'],
    dimensions: { length: 10, width: 8, height: 15, weight: 0.5 },
    costPrice: 600,
    sellPrice: 900,
    discountable: true,
    taxable: true,
    stock: 35,
    minStock: 10,
    maxStock: 70,
    unit: 'liter',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Sand Papers
  {
    categoryId: 27,
    sku: 'SAND-80-001',
    name: 'Sand Paper 80 Grit',
    brand: 'Generic',
    description: '80 grit sand paper',
    material: 'Paper + Abrasive',
    color: ['#78716C'],
    dimensions: { length: 23, width: 28, height: 0.1, weight: 0.1 },
    costPrice: 50,
    sellPrice: 80,
    discountable: true,
    taxable: true,
    stock: 200,
    minStock: 50,
    maxStock: 500,
    unit: 'sheet',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  {
    categoryId: 27,
    sku: 'SAND-120-001',
    name: 'Sand Paper 120 Grit',
    brand: 'Generic',
    description: '120 grit sand paper',
    material: 'Paper + Abrasive',
    color: ['#78716C'],
    dimensions: { length: 23, width: 28, height: 0.1, weight: 0.1 },
    costPrice: 50,
    sellPrice: 80,
    discountable: true,
    taxable: true,
    stock: 200,
    minStock: 50,
    maxStock: 500,
    unit: 'sheet',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  // Deco Paints
  {
    categoryId: 28,
    sku: 'PAINT-1L-001',
    name: 'Decorative Paint 1L',
    brand: 'Generic',
    description: 'Premium decorative paint',
    material: 'Paint',
    color: ['#FFFFFF'],
    dimensions: { length: 10, width: 10, height: 20, weight: 1 },
    costPrice: 1500,
    sellPrice: 2200,
    discountable: true,
    taxable: true,
    stock: 40,
    minStock: 10,
    maxStock: 80,
    unit: 'liter',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  },
  {
    categoryId: 28,
    sku: 'PAINT-4L-001',
    name: 'Decorative Paint 4L',
    brand: 'Generic',
    description: 'Premium decorative paint 4 liter',
    material: 'Paint',
    color: ['#FFFFFF'],
    dimensions: { length: 18, width: 18, height: 25, weight: 4 },
    costPrice: 5000,
    sellPrice: 7200,
    discountable: true,
    taxable: true,
    stock: 25,
    minStock: 5,
    maxStock: 50,
    unit: 'can',
    images: [],
    status: 'active',
    featured: false,
    createdAt: new Date()
  }
];

export async function seedDatabase() {
  const userCount = await db.users.count();
  if (userCount === 0) {
    await db.users.bulkAdd(defaultUsers);
    console.log('Seeded default users');
  } else {
    // Ensure the 3 custom users exist
    const customUsers = [
      {
        name: 'Saadullah',
        username: 'Saadullah',
        password: bcrypt.hashSync('saad1234', 10),
        role: 'admin' as const,
        email: 'saadullah@furnicraft.com',
        phone: '+92-300-0000001',
        status: 'active' as const,
        permissions: ['dashboard', 'pos', 'products', 'inventory', 'reports', 'staff', 'customers'],
        createdAt: new Date()
      },
      {
        name: 'Samiullah',
        username: 'Samiullah',
        password: bcrypt.hashSync('sami0987', 10),
        role: 'admin' as const,
        email: 'samiullah@furnicraft.com',
        phone: '+92-300-0000002',
        status: 'active' as const,
        permissions: ['dashboard', 'pos', 'products', 'inventory', 'reports', 'staff', 'customers'],
        createdAt: new Date()
      },
      {
        name: 'Abdullah',
        username: 'Abdullah',
        password: bcrypt.hashSync('abd4567', 10),
        role: 'admin' as const,
        email: 'abdullah@furnicraft.com',
        phone: '+92-300-0000003',
        status: 'active' as const,
        permissions: ['dashboard', 'pos', 'products', 'inventory', 'reports', 'staff', 'customers'],
        createdAt: new Date()
      }
    ];

    for (const user of customUsers) {
      const existing = await db.users.where('username').equals(user.username).first();
      if (!existing) {
        await db.users.add(user);
        console.log(`Added user: ${user.username}`);
      }
    }
  }

  const categoryCount = await db.categories.count();
  if (categoryCount === 0) {
    await db.categories.bulkAdd(defaultCategories);
    console.log('Seeded default categories');
  }

  const productCount = await db.products.count();
  if (productCount === 0) {
    await db.products.bulkAdd(sampleProducts);
    console.log('Seeded sample products');
  }

  const settingsCount = await db.settings.count();
  if (settingsCount === 0) {
    await db.settings.bulkAdd([
      { key: 'taxRate', value: '17' },
      { key: 'businessName', value: 'FurniCraft Furniture' },
      { key: 'receiptHeader', value: 'Thank you for shopping with FurniCraft!' },
      { key: 'receiptFooter', value: 'Visit us at www.furnicraft.com' },
      { key: 'currency', value: 'PKR' }
    ]);
    console.log('Seeded default settings');
  }
}
